### ISSUE TITLE
Problem with RequestActivityTest

### ISSUE THREAD

**Issue by cyw617** [cyw617/taxi#38]
Below is the current (non-committed) RequestActivityTest.java

```
package comp3111h.anytaxi.customer.test;

import android.content.Context;
import android.content.Intent;
import android.test.ActivityUnitTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.view.ContextThemeWrapper;
import android.widget.Button;

import comp3111h.anytaxi.customer.R;
import comp3111h.anytaxi.customer.RequestActivity;

public class RequestActivityTest extends ActivityUnitTestCase<RequestActivity>{

    private Context rContext; 

    public RequestActivityTest() {
        super(RequestActivity.class);
    }

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        rContext = getInstrumentation().getTargetContext();

        // set theme for AppCompat support
        setActivityContext(new ContextThemeWrapper(rContext, R.style.AppTheme));

        // onCreate() will be called for the activity
        Intent intent = new Intent(rContext, RequestActivityTest.class);

        startActivity(intent, null, null);
    }

    @SmallTest
    public void testOnRequestListener() {
        getActivity().onStart();

        Button requestButton = (Button) getActivity().findViewById(R.id.request_btn);

        assertNotNull("Request button is not found.", requestButton);

        requestButton.performClick();

        final Intent redirect = getStartedActivityIntent();
        assertNotNull("No activity is started.", redirect);
        assertEquals(redirect.getComponent().getShortClassName(), ".TrackingActivity");
    }
}
```

When I run this simple test case, it throws an ERROR:

```
android.view.InflateException: Binary XML file line #7: Error inflating class fragment
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:773)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:815)
at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
at android.view.LayoutInflater.inflate(LayoutInflater.java:465)
at android.view.LayoutInflater.inflate(LayoutInflater.java:416)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:341)
at android.app.Activity.setContentView(Activity.java:1923)
at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:216)
at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:111)
at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:76)
at comp3111h.anytaxi.customer.RequestActivity.onCreate(RequestActivity.java:56)
at android.app.Activity.performCreate(Activity.java:5065)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at android.test.ActivityUnitTestCase.startActivity(ActivityUnitTestCase.java:158)
at comp3111h.anytaxi.customer.test.RequestActivityTest.setUp(RequestActivityTest.java:32)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.IllegalStateException: Not on the main thread
at maps.k.o.b(Unknown Source)
at maps.i.g.b(Unknown Source)
at maps.e.al.a(Unknown Source)
at maps.e.al.n(Unknown Source)
at maps.e.al.a(Unknown Source)
at maps.e.bh.a(Unknown Source)
at maps.e.bg.a(Unknown Source)
at etu.onTransact(SourceFile:107)
at android.os.Binder.transact(Binder.java:326)
at com.google.android.gms.maps.internal.IMapFragmentDelegate$a$a.onCreateView(Unknown Source)
at com.google.android.gms.maps.SupportMapFragment$a.onCreateView(Unknown Source)
at com.google.android.gms.dynamic.a$4.b(Unknown Source)
at com.google.android.gms.dynamic.a.a(Unknown Source)
at com.google.android.gms.dynamic.a.onCreateView(Unknown Source)
at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:900)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1184)
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:291)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
... 23 more
```

I googled the error, but nothing helped. Therefore, I post it here to see if anyone can help.
Since the problem originates at onCreate(), test cases cannot run unless it is fixed. :(

P.S. I have changed the MapFragment to SupportMapFragment for compatability (see commit d3da249ba696eddd45dba9d4236141e11f29f51a)

**Comment by cyw617** [comment]
It is frustrating because the same error does not exist in the App...It seems to be the problem of unit test.

**Comment by cyw617** [comment]
In particular, the app throws the error after running <code>startActivity(intent, null, null);</code> in setup().

**Comment by hongzimao** [comment]
Now request activity test has error 'Not on the main thread'
